name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to be released'
        required: true
      release_type:
        type: choice
        description: 'sdk to publish (prod or dev)'
        required: true
        default: prod
        options:
          - prod
          - dev

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          registry-url: 'https://registry.npmjs.org/'

      - name: Install dependencies
        run: npm ci

      - name: Version update
        run: |
          echo "Bumping version to ${{ github.event.inputs.version }}"
          npm version ${{ github.event.inputs.version }} --no-git-tag-version

      - name: Update package name (prod or dev)
        run: |
          if [ "${{ inputs.release_type }}" = "dev" ]; then
          echo "Updating package name to notifly-js-sdk-dev..."
          node scripts/update_package_name.js notifly-js-sdk-dev
          else
          echo "Updating package name to notifly-js-sdk..."
          node scripts/update_package_name.js notifly-js-sdk
          fi

      - name: Read Changelog
        id: read_changelog
        if: ${{ !endsWith(github.event.inputs.version, 'SNAPSHOT') }}
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ github.event.inputs.version }}

      - name: Create GitHub Release
        if: steps.read_changelog.outputs.changes
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          body: ${{ steps.read_changelog.outputs.changes }}
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build package
        run: npm run build

      - name: Publish to npm
        run: |
          if [ "${{ inputs.release_type }}" = "dev" ]; then
            echo "Publishing to notifly-js-sdk-dev..."
            npm publish
          else
            echo "Publishing to notifly-js-sdk..."
            npm publish
          fi
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
