name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to be released'
        required: true

jobs:
  release:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: 'https://registry.npmjs.org'

      - name: Upgrade npm
        run: npm install -g npm@11.5.1

      - name: Install dependencies
        run: npm ci

      - name: Version update
        continue-on-error: true
        run: |
          echo "Bumping version to ${{ github.event.inputs.version }}"
          npm version ${{ github.event.inputs.version }} --no-git-tag-version

      - name: Read Changelog
        id: read_changelog
        if: ${{ !endsWith(github.event.inputs.version, 'SNAPSHOT') }}
        uses: mindsers/changelog-reader-action@v2
        with:
          version: ${{ github.event.inputs.version }}

      - name: Create GitHub Release
        if: steps.read_changelog.outputs.changes
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          body: ${{ steps.read_changelog.outputs.changes }}
          allowUpdates: true
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build package
        run: npm run build

      - name: Publish to npm
        run: |
          if [ "${{ contains(github.event.inputs.version, 'beta') }}" = "true" ]; then
            npm publish --provenance --access public --tag beta
          else
            npm publish --provenance --access public
          fi
